'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});

(function () {
    var enterModule = require('react-hot-loader').enterModule;

    enterModule && enterModule(module);
})();

// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:75c318fc-8d9b-4659-8a64-9c245b1317aa',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'webapp-hosting-mobilehub-1609355042',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ir6xd9i58uub.cloudfront.net',
    'aws_mobile_analytics_app_id': 'ecd413d70e9e4dee900c59e38cb1bd45',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '022c12be-b5b7-4024-abd0-21fdb994d920',
    'aws_project_name': 'web-app-1.0',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'webapp-mobilehub-1609355042',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'webapp-userfiles-mobilehub-1609355042',
    'aws_user_files_s3_bucket_region': 'us-east-2',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-2_8qMRGnVK5',
    'aws_user_pools_web_client_id': '1ka2va2t5c853toa0us7rurmkn'
};

var _default = awsmobile;
exports.default = _default;
;

(function () {
    var reactHotLoader = require('react-hot-loader').default;

    var leaveModule = require('react-hot-loader').leaveModule;

    if (!reactHotLoader) {
        return;
    }

    reactHotLoader.register(awsmobile, 'awsmobile', 'src/aws-exports.js');
    reactHotLoader.register(_default, 'default', 'src/aws-exports.js');
    leaveModule(module);
})();

;